spring:
  application:
    name: wallet-api
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db?createDatabaseIfNotExist=true
    username: nabgha
    password: 44026676
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
